### ISSUE TITLE
Bug for concating the MNI and HUP data

### ISSUE THREAD

**Issue by hxliu4mcgill** [jbernabei/iEEG_atlas_dev#8]
Hi your work is a valuable.  
But I found a bug in your code.
At very beginning I use MNI data in your code. I used the unprocessed .mat data after downloading the MNI dataset to replace the MNI_atlas_new.mat in your demo code. At first it works. Bug when calculating the power spectral density and FC, some bugs appear. I found that it is because the 51, 86, 95, and 105 patients were replaced from MNI dataset. But the sequence numbers of MNI patients are still end with 110, not 106. So when concating the HUP behind MNI, the two datasets will have overlap on patients 107-110.

Maybe would you like to share how the  MNI_atlas_new.mat is made ? Or would you like to share the MNI_atlas_new.mat directly ?

**Comment by jbernabei** [comment]
Thank you for your comment. The MNI_atlas_new file I used was exactly the same as the original MNI dataset just with the patient IDs adjusted so that it ended with 106 (i.e. filling in the empty subjects 51, 86, 95, and 105). This way it avoids any overlap between HUP and MNI, and also made it simpler to write the code when I was looping through subjects. Hope this helps!
